### ISSUE TITLE
[FIXED] Guardian fleet redesign

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#1]
The new hex limit kills the Guardian, and is probably not too good for the Lecythos and Vastabat. I'll need to make new designs for them...

**Comment by Alarcarr** [comment]
We need to nerf the guardian anyway somehow the Fleet is now 120M strenght and the Range of that shit is too big.

**Comment by DaloLorn** [comment]
It's now 120M strength because of the changes to the design system. Like I said in the other thread, we have to redo all our balancing.

Edit: Also, do I hear that it's too OP for the person who cranked up the size to 240% of what I gave him? ;D

**Comment by Alarcarr** [comment]
But is op now before was fine ,
