### ISSUE TITLE
Increasing turret effectiveness when placed on orbitals

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#10]
Copied from the spreadsheet.

One question: Are turrets also supposed to buff station HP, or just orbitals? I'm not sure I know how to do the former.

**Comment by DaloLorn** [comment]
Alar, I'd like an answer to this. :P

**Comment by DaloLorn** [comment]
Earth to Alar, come in, Alar.

**Comment by DaloLorn** [comment]
Alaaaar...

**Comment by Alarcarr** [comment]
Idc

**Comment by DaloLorn** [comment]
Thank you. I'll get around to finishing this sometime during this week. I'll also handle the other issues on the list.

**Comment by DaloLorn** [comment]
I've doubled the range of orbital-mounted turrets. I can probably implement the HP buff, but this was easier and seemed more necessary. (Seriously, 300 units for the laser? That sort of works for ships, but it's just ridiculous for an orbital.)

**Comment by DaloLorn** [comment]
Seeing as you don't seem to be complaining about my solution (yet? :P), I'm closing the issue for now.
