### ISSUE TITLE
Defensive Matrix

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#12]
Copied from the spreadsheet.

For the moment, I'm thinking about letting a ship with the right subsystem grant a temporary shield to any other ship, including itself.

**Comment by DaloLorn** [comment]
Should have this sometime this week. Maybe next week.

_walks away_ MUST. NOT. GET. SIDETRACKED. AGAIN.

**Comment by Alarcarr** [comment]
Pre Added to the grid .

**Comment by DaloLorn** [comment]
Looks like it's done.
