### ISSUE TITLE
Support Quantum amor broken

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/ABEMMOD#15]

**Comment by DaloLorn** [comment]
Is it, perhaps, because you copy-pasted the whole thing from Plate Armor and then gave a massive HP buff to said Plate Armor? _rolls eyes_

**Comment by Alarcarr** [comment]
Probably i will fix it today.You have  something to correct?

:-)

**Comment by DaloLorn** [comment]
If you fixed it, you should have closed it, no? :P

_swings hammer_
