### ISSUE TITLE
Push out hotfix for r4297

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#16]
The mod is physically incapable of running on r4297 until that patch is released.

This is more than just broken gameplay. (Though I foresee a lot of work in that area as well, seeing as the new traits each have their quirks that ABEM's tech trees and stuff don't account for.)

**Comment by DaloLorn** [comment]
*takes deep breath* PUSH IT ALREADY!!!!!1!

Seriously, though. Push it.

**Comment by Alarcarr** [comment]
Oks now i will

**Comment by DaloLorn** [comment]
I still think we should have acted proactively instead of reactively, but whatever.
