### ISSUE TITLE
Update files to account for changes in r4297 and later

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#17]
I don't know how you want to handle some of these issues, and I can handle most of the others, but I'm just listing them all here:
- [x] Certain techs on the tech tree are dynamically replaced by other techs in the case of some races - however, some ABEM techs are not affected when they should be (This one might have to be yours, though I can theoretically take care of it)
- [x] Improved Command Deck might need some kind of replacement for Verdant - 'Stimulant Sinew Cluster', perhaps? (Needs more discussing, I guess)
- [x] Prevent Outposts from being constructed by Evangelical Engineering Bays (I can take care of this, though I'm not sure what to replace it with - Star Temples, perhaps?)

**Comment by DaloLorn** [comment]
- Home systems must not have moons, except the level 1 planet which must have a moon forcibly spawned

**Comment by DaloLorn** [comment]
- [DONE] Non-FTL, non-lifestyle non-government traits needed removal, already did it before writing this

**Comment by DaloLorn** [comment]
- Fling beacons must use BreakOrbitOnFTL() hook to avoid being pulled into FTL by flinging planets
- Flak cannons may or may not need to become non-spillable damage. It's up to you, really.
- Damage resistance must now account for Muon Cannons.

**Comment by DaloLorn** [comment]
- Adjust weapon effectors to only target damageable enemies and, when appropriate, auto-target enemy freighters

**Comment by DaloLorn** [comment]
Wiped some of the previous issues, seeing as they're completely solved.
- [x] Vanilla gates are now designable stations. We must decide how to react to this.

**Comment by Alarcarr** [comment]
gates are designable stations on abem too just remove the old gate subsystem.So we start usiing the vanilla ones and maybe change the oither stations to fit into that role.

**Comment by DaloLorn** [comment]
New commit to adapt to: https://github.com/BlindMindStudios/SR2Beta/commit/42f2feb497f567156ffbc36b48a78093a8770c4d
- [x] Remove design_stats.txt, migrate our custom stats into a separate file in data/design_stats
- [x] [CRITICAL] Add 'Cargo' references to objects.txt, adjust Asteroid object
- [x] [CRITICAL] Adjust a whole lot of systems to use Cargo instead of resources when spawning asteroids, and/or spawn asteroids in a different manner. This could kill the Pretiosian Nebula...

**Comment by DaloLorn** [comment]
- [x] [CRITICAL] Add BaseSupport to all planet levels in order to allow planets to spawn correctly.

**Comment by DaloLorn** [comment]
- [x] [CRITICAL] Adjust Star script using commit https://github.com/BlindMindStudios/SR2Beta/commit/5c258523f4cda0a79ebc18c4b353420eb08a4a60 as a baseline
- [x] Add 'classes' to research nodes, as per commit https://github.com/BlindMindStudios/SR2Beta/commit/19e33c70ff20b48d773ec1b63abb5b575165fdec
- [x] [CRITICAL] Fix 'Recall' in accordance with commit https://github.com/BlindMindStudios/SR2Beta/commit/2951488b0c298368ae0e7c32608fbca4384b8cc2

**Comment by DaloLorn** [comment]
- [x] Make sure the nebula guide is up to date

**Comment by DaloLorn** [comment]
- Adjust ability targeting for things such as boarding parties. Also adjust Radioactive Nebula not to affect asteroids.

**Comment by DaloLorn** [comment]
New commit: https://github.com/BlindMindStudios/SR2Beta/commit/4f4bbe9068375613ab5396ea1dfaaa827acbebb2
- [x] [CRITICAL] Add 'Resource' references to objects.txt, readjust asteroid spawning once again
- [x] Re-update nebula guide

**Comment by DaloLorn** [comment]
- [x] Update artifacts to use ArtifactAdvanced model where appropriate

Commit https://github.com/BlindMindStudios/SR2Beta/commit/4be0ff37983849430caf6afb90e8ccab12dd15bb:
- [x] [CRITICAL] Update engines to have turn thrust, as well as providing appropriate tags.
- [x] Update localization for any engines relocalized by ABEM.

**Comment by DaloLorn** [comment]
- [x] [CRITICAL] Update damage reduction scripts; replace all instances of DT_IgnoreDR with DF_IgnoreDR. Also, remove all references to QuadDRPenalty.

**Comment by DaloLorn** [comment]
- [x] [CRITICAL] Update FlagshipHull so that Devout can build Shrines.

**Comment by DaloLorn** [comment]
- [x] Check if maintenance needs tweaking as per commit https://github.com/BlindMindStudios/SR2Beta/commit/cc27d2db3eebd1db7c1860a8587a0aab5f60bb7a
- [x] Use Commerce Station model as per commit https://github.com/BlindMindStudios/SR2Beta/commit/05877f4e68f7ccb184f8f45cb99f2267dabf6bf6
- [x] Investigate relevance of changes in commit https://github.com/BlindMindStudios/SR2Beta/commit/bccf0bfa54c4dc69f162eb9a50d03e043933b480

**Comment by DaloLorn** [comment]
- [x] Change FTL Jammer to use 0.15 FTL again.
- [x] Adjust all cargo-related stuff as per commit https://github.com/BlindMindStudios/SR2Beta/commit/f48e1ff1169b718f576598278c87cbeaa7e1756b

**Comment by DaloLorn** [comment]
Uh, resolved the Verdant in the OP?

**Comment by DaloLorn** [comment]
Yikes.
- [x] Fix Mono. https://github.com/BlindMindStudios/SR2Beta/commit/6fd8c8b8e556305f80e296e30c9fef98c275f528
- [ ] Adapt to Ablative Armor changes in https://github.com/BlindMindStudios/SR2Beta/commit/39c75128f463762e2805dfc4df88547698e2532e, https://github.com/BlindMindStudios/SR2Beta/commit/e0f84cbeac147c094f2bcfc1caf35375f8d7e3a7 and https://github.com/BlindMindStudios/SR2Beta/commit/2e63c566ef50dc5ffe62776b2a95bb8252af2bda
- [x] Adapt to Self-Destruct Device changes in https://github.com/BlindMindStudios/SR2Beta/commit/7d6ddf06b991c3d49db2f59f9c093eda7fca9b5c and https://github.com/BlindMindStudios/SR2Beta/commit/94497a2417e32a99a7c2e2f9800ceefc2ddb8065
- [x] Adapt to turret changes in https://github.com/BlindMindStudios/SR2Beta/commit/0905363149a6e9f06a1da403ddb3a7ad5070c030 and https://github.com/BlindMindStudios/SR2Beta/commit/2e63c566ef50dc5ffe62776b2a95bb8252af2bda
- [x] Add support modifiers as per https://github.com/BlindMindStudios/SR2Beta/commit/04ebed425a8429034f1b2551bc776078b01adfa2, https://github.com/BlindMindStudios/SR2Beta/commit/e3f81fcc15326ee7c91194822543838181c512a4 and https://github.com/BlindMindStudios/SR2Beta/commit/9e6646e72899987e71f43a2878d224871df7a1f5

**Comment by Alarcarr** [comment]
Dont touch nothing about armor.

**Comment by DaloLorn** [comment]
Uh, I expect it won't be coming out for a while, but I feel I should create the references anyway so I don't forget:
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/ba794ca75e8de6991c9c93a470d5ac71a24c23ac
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/ab054bc44784b4107395d4d809ae21bca9a762de
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/930c957123eb427a034d01a0e7a352d2b82fc391
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/3e4a614cacccacee24991c46e779927e392e6b4c

**Comment by DaloLorn** [comment]
Sheesh, they're not pulling any punches:
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/af0a3bd3342c9fc0e7a03993b46e9f8b5cc07364
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/af86b5a172706460362d119af3798b1a750b1fe4
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/f2f6b5820265baaaa7385896d2268c06a21616df
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/8b7ddea8464a44fb436e968283e8e78da925121c

**Comment by DaloLorn** [comment]
Wheeeee!
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/996a35078f970620be6f1efbb46f9565e6cabb90
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/f234f090999be42e7254530af2cf76009ed12ed8
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/7d7947efb6d1e97c584341f76a91f195cb2cf963
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/a0f66dca6a637e67476a0b2809c9de6072d7ce5b
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/d5b253690cf867610ff36b9b040de466e2595dcc

**Comment by DaloLorn** [comment]
Oh, this is just beautiful, so much potential:
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/e1e08f8c1636ab0099aee786ea1502050d772e23
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/fc8e0a10cdda80291b96bbc8dee69286ad657781
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/8125a84be9821c4219839a38b8feb6d287050bc8

**Comment by DaloLorn** [comment]
- [ ] https://github.com/BlindMindStudios/SR2Beta/commit/d1bc1d0d1d3b4ac7084a88d9022bc99a2fe2e3b2
