### ISSUE TITLE
Rework Ringworlders.

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#27]
- [x] Instead of destroying planets and having temporary access to a resource, Ringworlders steal the resources from the target planet after a certain period (300 seconds?), tranferring them to one of their Ringworlds while rendering the target barren.
- [x] Colonizing planets aside from the Ringworld is impossible. Similarly, non-Ringworld planets are immediately abandoned upon capture. Needless to say, constructing an Artificial Planetoid is not possible.
- [x] Constructing five 'Hyperfield Data Collators' on five separate Ringworlds automatically causes the Ringworlders to win the game. (The number of Ringworlds required is subject to change, and I'm not sure if we should put the HDC on the tech grid.)
- [x] Other players are notified of the construction of each individual HDC.
- [x] Resource stealing is prepared for by a special ship, which adds a status to the target planet after the abovementioned period. Any Ringworld can then use an ability to finish the process and receive the planet's resources. 
  - [x] 'Artificial Planetoid', 'Ringworld', 'Altar', 'Water' and 'Soylent' resources cannot be stolen, as they are either native to the planet's method of construction (AP and Ringworld) or linked to a building (Altar, Hydrogenator and Megafarm). Water from Comets is not affected by this, though.

**Comment by DaloLorn** [comment]
Well, what do you think?

**Comment by Alarcarr** [comment]
If u wanna add a new race add it but u can let the reclusive ringworlders as it is.That being sad what u propose its unbalanced will need a lot of tweaking.

**Comment by DaloLorn** [comment]
Making a note in case I forget:

- [ ] Explain to Darloth that the 'destroyed planets remove themselves twice' bug he keeps mentioning on the Ringworlders' Workshop page was fixed back on the 30th of March *rolls eyes*

**Comment by DaloLorn** [comment]
This is finished.
