### ISSUE TITLE
Planetary Invasions ;Change capture method from supply to troops

### ISSUE THREAD

**Issue by Alarcarr** [Alarcarr/ABEMMOD#39]
Change how Invasion works and capturing works.

- [ ] New resource to be able to generate on planets "Troops" .This ones will be treated like Ore.Troops will need a imperial /building to train them and it will. 

- [ ] This new resource will have a Quality number dependant on how trained the troops are .

- [ ] Create /adapt a planet/resource to have an inpact on quality of the troops  created.

- [ ] Create Art for those things.

-----
More issues are gonna present just for the times this are included

**Comment by DaloLorn** [comment]
... [Feature creep](https://en.wikipedia.org/wiki/Feature_creep)...
