### ISSUE TITLE
Get back on track.

### ISSUE THREAD

**Issue by DaloLorn** [Alarcarr/ABEMMOD#41]
Okay, maybe we need to try approaching this whole FTL/Power revamp a bit more systematically.

As it is right now, you're haphazardly tacking on tons of new features while core functionality (like making the system work with the stuff we _already have_) goes untouched, forcing me to try to fix the 'haphazardly' part.

This in turn prevents me from helping with said core functionality, keeping the mod from working _at all_ in the meantime, making it difficult for you to test whether you made something seriously over/underpowered and outright impossible for me to release to the experimental build to get more feedback.

Finally, we get to where we are now. You're not committing anything, presumably because you're either waiting for me to fix your latest attempt at implementing yet another new feature or trying to fix it yourself, while I'm not doing anything because whenever I look at the files, I see a mountainous interconnected web of things I have to deal with. Which isn't particularly encouraging. (And, as usual, my ability to find other ways of spending my free time isn't helping. :/)

So, for now, we should focus on this:
- [ ] Add Power storage, generation or consumption to all relevant subsystems. You figure out the numbers and stuff, I'll deal with any backend stuff that hasn't been done yet (like making abilities drain Power via hooks, or Powered Armor consume power when soaking up damage).

**Comment by Alarcarr** [comment]
Problem right now is at is the power is just a intermediate that provide no gameplay changes , for that to be usefull combat dynamics need to be changed around power ,I was looking around the power files to try fix what I started but did not  managed to do that yet.

**Comment by DaloLorn** [comment]
Combat dynamics like what?

**Comment by DaloLorn** [comment]
TODO #579327:
- [ ] Create hook for shield regeneration boost. Add the option for Power consumption to be affected proportionally or disproportionally to the base consumption.
- [ ] Create hook(s) for Power consumption already!
